### ISSUE TITLE
Need redirect filter for cloudrive sign-in

### ISSUE THREAD

**Issue by AaronMPeters** [Jdhaimson/smilealways#20]
It appears that a filter was added in [this comit](https://github.com/Jdhaimson/smilealways/commit/adcd2f1afe878ec1a594779bb4201467c5b8ff73) so that simply visiting https://www.amazon.com/clouddrive/home will not redirect to smile. However, if the user has to sign in to cloud drive (by clicking the 'Hello, Sign In' link in the top right), a 404 will occur. The URL that the signin redirects to is:
https://www.amazon.com/clouddrive?sf=1&ref_=cd_home_sign_bnh

Steps to reproduce:
1. Visit [cloud drive home page](https://www.amazon.com/clouddrive/home)
2. Click the drop down in the upper-right corner which says 'Hello, Sign In' and then click the 'Sign In' link
3. Receive the 404 error page

**Comment by Jdhaimson** [comment]
Thanks for submitting this, the latest version (.90) should fix this problem.  Please let me know there are any other issues!
