### ISSUE TITLE
Feature: Toggle on/off

### ISSUE THREAD

**Issue by disconn3ct** [Jdhaimson/smilealways#22]
Is it possible to toggle on/off? Smile interferes with the affiliate link generator. (I know the link can be generated manually but it is a lot easier to use the built-in one.)

**Comment by bbodenmiller** [comment]
How can I test the affiliate link generator to create a rule to prevent Smile Always from interfering?

**Comment by disconn3ct** [comment]
I completely missed your message, but it looks like something along the way has fixed it.

For reference, you can sign up for free at https://affiliate-program.amazon.com/ and then there is a link generator bar at the top of every Amazon page (products, searches, etc.)
