### ISSUE TITLE
Print return label from email link does not work

### ISSUE THREAD

**Issue by ptr727** [Jdhaimson/smilealways#23]
Return package email contains print label link:
https://www.amazon.com/gp/f.html?C=blah&K=blah&R=blah&T=C&U=https%3A%2F%2Fwww.amazon.com%2Freturns%2Flabel%2F9ceeablah-blah%2FrmaID%2FDckf6ZftRRMA%3Fref_%3Dpe_1811570_blah_E_Label_Page&A=blah&H=blah&ref_=pe_1811570_136791410_E_Label_Page

Result is smile homepage instead of printing label page.

**Comment by jfim** [comment]
Encountered the same issue today.

**Comment by bbodenmiller** [comment]
Same here.

**Comment by bbodenmiller** [comment]
Worth noting, in my email the link was listed as https://www.amazon.com/gp/orc/rml/DPXHGDfMRRMA but clicking it actually took me to https://www.amazon.com/gp/f.html?C=3GG4DES2VDURU&K=A1XW8V80Q4YRCU&R=3G8BEQXHG6QHZ&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fgp%2Forc%2Frml%2FDPXHGDfMRRMA%3Fref_%3Dpe_584750_33951330&A=WHUJOQOSKTAWYM0AIIKIDM1XB9GA&H=ZXYH6LZ5OBKKKCOUEFWN3ZEEZ9GA&ref_=pe_584750_33951330. If I copy & paste https://www.amazon.com/gp/orc/rml/DPXHGDfMRRMA it works fine.

**Comment by ptr727** [comment]
Delayed shipping email, confirm I still want this item link also does not work:
https://www.amazon.com/gp/f.html?C=U2OSJ9PC7UL7&K=AYEW9BEYUKTOM&R=R1NH8J1BVVCD&T=C&U=http%3A%2F%2Fwww.amazon.com%2Fgp%2Fcss%2Forder%2Fedit.html%3FuseCase%3Dapprove%26orderID%3D104-8181905-9483452%26ref%3Dfxm_3_0_on_sh%26ref_%3Dpe_861660_138884010&A=VUMT2ON1H2ZSJZNJPPKPNOACKSCA&H=IA4ZLBLDSZUMFT5MYC8QAR5EITQA&ref_=pe_861660_138884010

**Comment by bbodenmiller** [comment]
@ptr727 I think https://github.com/Jdhaimson/smilealways/pull/25 should fix that also. Hopefully @Jdhaimson can review, merge, and release soon.
