### ISSUE TITLE
Warnings due to Conflict with HTTPS Everywhere

### ISSUE THREAD

**Issue by Soundvessel** [Jdhaimson/smilealways#37]
I love your plugin but it occasionally throws warnings because of a conflict with the HTTPS Everywhere extension by the EFF https://www.eff.org/https-everywhere. Is it possible to make them play nicely together?

`This extension failed to redirect a network request to http://smile.amazon.com/o/ASIN/1909263079/sciencefriday/?sa-no-redirect=1 because another extension (HTTPS Everywhere) redirected it to https://www.amazon.com/o/ASIN/1909263079/sciencefriday/.`

**Comment by Piccirello** [comment]
The Chrome web store still has version 0.91, whereas the HTTPS Everywhere fix is in 0.92.

**Comment by tastyratz** [comment]
Another vote for that here. This has been driving me nuts for a long time. I had no idea it's been fixed!!

This is married to the HTTPSE issue here:
 https://github.com/EFForg/https-everywhere/issues/6034

**Comment by Piccirello** [comment]
Can someone provide insight into why this was closed? The version on the web store is still 0.91.

**Comment by delitzer** [comment]
Yes, I closed it when I pushed 0.92 to the Chrome Web Store a couple hours
ago. The new version is undergoing review but will be live in the store
soon.

**Comment by Piccirello** [comment]
Excellent, thank you!
