### ISSUE TITLE
Conflicting errors between this and https everywhere

### ISSUE THREAD

**Issue by o-fernandez** [Jdhaimson/smilealways#38]
I use the https everywhere extension (https://www.eff.org/https-everywhere) and sometimes I get an error message on SmileAlways saying that there's a conflict between the two apps. It seems that the two apps try to modify the URL, one to take me to https:// and the other to smile.amazon.com, but somehow they clash. Is there a way to ensure that this doesn't happen? 

![screen shot 2017-03-31 at 3 14 23 pm](https://cloud.githubusercontent.com/assets/13389997/24571255/caad1b1c-1624-11e7-99a3-c5d314152116.png)

**Comment by delitzer** [comment]
Yep, it's a known issue. I just pushed a fix in v0.92 to the Chrome Web
Store. It's currently pending review but will hopefully be live soon.
