### ISSUE TITLE
Can't sign in with extension enabled

### ISSUE THREAD

**Issue by jburdge** [Jdhaimson/smilealways#8]
If you are logged out of Amazon, a large number of things are broken on Amazon's website with this extension enabled.  This is related to bug #7.

Reproduce:
- enable extension in incognito mode
- open incognito tab
- go to a product url like http://smile.amazon.com/gp/product/B002L4EXGA
- try to sign in using the link at the top right

I found a few other errors when logged out as well, like when I searched for the above link, I got to a google search that had an amazon advertisement that linked to this url: http://goo.gl/xYWtGv  That results in a redirect loop with the extension enabled in incognito mode.

**Comment by bbodenmiller** [comment]
Appears this is no longer an issue.
